version: '2.3'

services:
  ruqqus:
    build:
      context: .
    volumes:
      - "./:/opt/ruqqus/service"
    env_file:
      - /opt/env.env
    links:
      - "redis"
      - "postgres"
    ports:
      - target: 8000
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    command: bash -c "
        redis-server /usr/local/etc/redis/redis.conf
        && redis-server config set dir "/usr/local"
      "
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  postgres:
    image: postgres:12.3
    volumes:
      - "/opt/postgres.conf"
      - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
      - "./seed-db.sql:/docker-entrypoint-initdb.d/10-seed-db.sql"
    ports:
      - "5432:5432"
